[information]
name = "neobeans"
background = "dark"
author = 'Mike Mannix <mikemannix@gmail.com>'

[palette]
fg = '#ffffff'
bg = '#111111'

alt_fg = '#dedede'
alt_bg = '#1f1f1f'

line = '#292929'
dark_gray = '#292929'
gray = '#3d3d3d'
context = '#292929'
light_gray = '#5c5c5c'
menu_bg = '#292929'

red = '#e17373'
blue = '#96bddb'
vivid_blue = '#498dc1'
light_blue = '#b1d7f6'
green = '#94b978'
light_green = '#bddeab'
cyan = '#00988e'
orange = '#ff9d47'
yellow = '#ffb97b'
yellow_orange = '#ffdba0'
purple = '#fbdaff'
magenta = '#e1c0fa'

cursor_fg = '#292929'
cursor_bg = '#b1d7f6'

sign_add = '#94b978'
sign_change = '#b1d7f6'
sign_delete = '#e17373'

sign_add_alt = '#bddeab'
sign_change_alt = '#ff9d47'

error = '#e17373'
warn = '#ffb97b'
info = '#94b978'
hint = '#b1d7f6'

error_bg = '#292929'
warn_bg = '#292929'
info_bg = '#292929'
hint_bg = '#292929'

reference = '#292929'
success_green = '#94b978'
folder_blue = '#96bddb'


ui_blue = '#96bddb'
ui2_blue = '#5896c6'
ui3_blue = '#b3cfe5'
ui4_blue = '#d1e2ef'
ui5_blue = '#76a9d0'
ui_orange = '#ffb97b'
ui2_orange = '#ff9d47'
ui_purple = '#e1c0fa'

[Editor]
Normal = 'fg bg'
SignColumn = '- bg'
MsgArea = 'fg bg'
ModeMsg = 'fg alt_bg'
MsgSeparator = 'fg bg'
SpellBad = '- - c red'
SpellCap = '- - c yellow'
SpellLocal = '- - u green'
SpellRare = '- - u purple'
NormalNC = 'fg bg'
Pmenu = 'light_gray menu_bg'
PmenuSel = '- ui2_blue'
WildMenu = 'fg ui2_blue'
CursorLineNr = 'light_gray'
Folded = 'gray alt_bg'
FoldColumn = 'gray alt_bg'
LineNr = 'gray -'
FloatBoder = 'gray alt_bg'
Whitespace = 'bg'
VertSplit = 'gray bg'
CursorLine = '- alt_bg'
CursorColumn = '- alt_bg'
ColorColumn = '- alt_bg'
NormalFloat = '- alt_bg'
Visual = '- ui_blue'
VisualNOS = '- alt_bg'
WarningMsg = 'error bg'
DiffText = 'alt_bg sign_delete'
DiffAdd = 'alt_bg sign_add'
DiffChange = 'alt_bg sign_change u'
DiffDelete = 'alt_bg sign_delete'
QuickFixLine = '- ui2_blue'
PmenuSbar = '- alt_bg'
PmenuThumb = '- gray'
MatchWord = '- reference'
MatchParen = 'hint reference'
MatchWordCur = '- reference'
MatchParenCur = '- reference'
Cursor = 'cursor_fg cursor_bg'
lCursor = 'cursor_fg cursor_bg'
CursorIM = 'cursor_fg cursor_bg'
TermCursor = 'cursor_fg cursor_bg'
TermCursorNC = 'cursor_fg cursor_bg'
Conceal = 'gray'
Directory = 'folder_blue'
SpecialKey = 'blue - b'
ErrorMsg = 'error bg b'
Search = 'bg light_blue'
IncSearch = 'bg blue'
Substitute = '- ui2_orange'
MoreMsg = 'orange'
Question = 'orange'
EndOfBuffer = 'bg'
NonText = 'bg'
TabLine = 'light_gray line'
TabLineSel = 'fg line'
TabLineFill = 'line line'

[Code]
Comment = 'light_gray'
Variable = 'light_blue'
String = 'green'
Character = 'orange'
Number = 'light_green'
Float = 'light_green'
Boolean = 'blue'
Constant = 'vivid_blue'
Type = 'orange'
Function = 'yellow'
Keyword = 'blue'
Conditional = 'purple'
Repeat = 'purple'
Operator = 'fg'
PreProc = 'purple'
Include = 'purple'
Exception = 'purple'
StorageClass = 'cyan'
Structure = 'cyan'
Typedef = 'purple'
Define = 'purple'
Macro = 'blue'
Debug = 'red'
Title = 'blue - b'
Label = 'blue'
SpecialChar = 'orange'
Delimiter = 'fg'
SpecialComment = 'fg'
Tag = 'blue'
Bold = '- - b'
Italic = '- - i'
Underlined = '- - u'
Ignore = 'magenta - b'
Todo = 'magenta - b'
Error = 'error - b'
Statement = 'purple'
Identifier = 'fg'
PreCondit = 'purple'
Special = 'orange'

[Treesitter]
TSComment = 'green - i'
TSVariable = 'link:Variable'
TSString = 'link:String'
TSStringRegex = 'link:String'
TSStringEscape = 'link:String'
TSCharacter = 'link:String'
TSCharacterSpecial = 'link:SpecialChar'
TSNumber = 'link:Number'
TSFloat = 'link:Float'
TSBoolean = 'link:Boolean'
TSConstant = 'link:Constant'
TSConstBuiltin = 'link:Constant'
TSConstructor = 'link:Type'
TSType = 'link:Type'
TSInclude = 'link:Include'
TSException = 'link:Exception'
TSKeyword = 'link:Keyword'
TSKeywordReturn = 'link:Include'
TSKeywordOperator = 'link:Include'
TSKeywordFunction = 'link:Keyword'
TSFunction = 'link:Function'
TSFuncBuiltin = 'link:Type'
TSMethod = 'link:Function'
TSFuncMacro = 'link:Function'
TSConditional = 'link:Conditional'
TSRepeat = 'link:Repeat'
TSOperator = 'link:Operator'
TSPreProc = 'link:PreProc'
TSStorageClass = 'link:StorageClass'
TSStructure = 'link:Structure'
TSTypeDefinition = 'link:Typedef'
TSDefine = 'link:Define'
TSNote = 'link:Comment'
TSTodo = 'link:Todo'
TSDebug = 'link:Debug'
TSDanger = 'link:Error'
TSTitle = 'link:Title'
TSLabel = 'link:Label'
TSPunctDelimiter = 'link:Delimiter'
TSTagDelimiter = 'gray'
TSPunctBracket = 'link:Delimiter'
TSPunctSpecial = 'link:Delimiter'
TSTag = 'link:Tag'
TSStrong = 'link:Bold'
TSEmphasis = 'link:Italic'
TSUnderline = 'link:Underline'
TSStrike = '- - s'
TSStringSpecial = 'fg'
TSEnvironmentName = 'cyan'
TSVariableBuiltin = 'cyan'
TSConstMacro = 'vivid_blue'
TSTypeBuiltin = 'cyan'
TSAnnotation = 'blue'
TSNamespace = 'cyan'
TSSymbol = 'fg'
TSField = 'link:Variable'
TSProperty = 'light_blue'
TSParameter = 'light_blue'
TSParameterReference = 'light_blue'
TSAttribute = 'cyan'
TSText = 'fg'
TSTagAttribute = 'light_blue - i'
TSError = 'error'
TSWarning = 'warn'
TSQueryLinterError = 'error'
TSURI = 'cyan - u'
TSMath = 'yellow'
TSLiteral = 'orange'

[markdown]
markdownBlockquote = 'orange'
markdownCode = 'orange'
markdownCodeBlock = 'orange'
markdownCodeDelimiter = 'orange'
markdownH1 = 'link:Title'
markdownH2 = 'link:Title'
markdownH3 = 'link:Title'
markdownH4 = 'link:Title'
markdownH5 = 'link:Title'
markdownH6 = 'link:Title'
markdownHeadingDelimiter = 'blue'
markdownHeadingRule = 'fg - b'
markdownId = 'link:Identifier'
markdownIdDeclaration = 'blue'
markdownIdDelimiter = 'light_gray'
markdownLinkDelimiter = 'light_gray'
markdownBold = 'blue - b'
markdownItalic = 'link:Italic'
markdownBoldItalic = 'yellow - bi'
markdownListMarker = 'blue'
markdownOrderedListMarker = 'purple'
markdownRule = 'gray'
markdownUrl = 'cyan - t'
markdownLinkText = 'blue'
markdownFootnote = 'orange'
markdownFootnoteDefinition = 'orange'
markdownEscape = 'yellow'

[Whichkey]
WhichKey = 'purple'
WhichKeySeperator = 'green'
WhichKeyGroup = 'blue'
WhichKeyDesc = 'fg'
WhichKeyFloat = '- alt_bg'

[Git]
SignAdd = 'sign_add'
SignChange = 'sign_change'
SignDelete = 'sign_delete'
GitSignsAdd = 'sign_add'
GitSignsChange = 'sign_change'
GitSignsDelete = 'sign_delete'

[LSP]
DiagnosticHint = 'hint'
DiagnosticInfo = 'info'
DiagnosticWarn = 'warn'
DiagnosticError = 'error'
DiagnosticOther = 'ui_purple'
DiagnosticSignHint = 'link:DiagnosticHint'
DiagnosticSignInfo = 'link:DiagnosticInfo'
DiagnosticSignWarn = 'link:DiagnosticWarn'
DiagnosticSignError = 'link:DiagnosticError'
DiagnosticSignOther = 'link:DiagnosticOther'
DiagnosticSignWarning = 'link:DiagnosticWarn'
DiagnosticFloatingHint = 'link:DiagnosticHint'
DiagnosticFloatingInfo = 'link:DiagnosticInfo'
DiagnosticFloatingWarn = 'link:DiagnosticWarn'
DiagnosticFloatingError = 'link:DiagnosticError'
DiagnosticUnderlineHint = '- - c hint'
DiagnosticUnderlineInfo = '- - c info'
DiagnosticUnderlineWarn = '- - c warn'
DiagnosticUnderlineError = '- - c error'
DiagnosticSignInformation = 'link:DiagnosticInfo'
DiagnosticVirtualTextHint = 'hint hint_bg'
DiagnosticVirtualTextInfo = 'info info_bg'
DiagnosticVirtualTextWarn = 'warn warn_bg'
DiagnosticVirtualTextError = 'error error_bg'

LspDiagnosticsError = 'error'
LspDiagnosticsWarning = 'warn'
LspDiagnosticsInfo = 'info'
LspDiagnosticsInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsHint = 'hint'
LspDiagnosticsDefaultError = 'link:LspDiagnosticsError'
LspDiagnosticsDefaultWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsDefaultInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsDefaultInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsDefaultHint = 'link:LspDiagnosticsHint'
LspDiagnosticsVirtualTextError = 'link:DiagnosticVirtualTextError'
LspDiagnosticsVirtualTextWarning = 'link:DiagnosticVirtualTextWarn'
LspDiagnosticsVirtualTextInformation = 'link:DiagnosticVirtualTextInfo'
LspDiagnosticsVirtualTextInfo = 'link:DiagnosticVirtualTextInfo'
LspDiagnosticsVirtualTextHint = 'link:DiagnosticVirtualTextHint'
LspDiagnosticsFloatingError = 'link:LspDiagnosticsError'
LspDiagnosticsFloatingWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsFloatingInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsFloatingInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsFloatingHint = 'link:LspDiagnosticsHint'
LspDiagnosticsSignError = 'link:LspDiagnosticsError'
LspDiagnosticsSignWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsSignInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsSignInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsSignHint = 'link:LspDiagnosticsHint'

NvimTreeLspDiagnosticsError = 'link:LspDiagnosticsError'
NvimTreeLspDiagnosticsWarning = 'link:LspDiagnosticsWarning'
NvimTreeLspDiagnosticsInformation = 'link:LspDiagnosticsInfo'
NvimTreeLspDiagnosticsInfo = 'link:LspDiagnosticsInfo'
NvimTreeLspDiagnosticsHint = 'link:LspDiagnosticsHint'

LspDiagnosticsUnderlineError = 'link:DiagnosticUnderlineError'
LspDiagnosticsUnderlineWarning = 'link:DiagnosticUnderlineWarn'
LspDiagnosticsUnderlineInformation = 'link:DiagnosticUnderlineInfo'
LspDiagnosticsUnderlineInfo = 'link:DiagnosticUnderlineInfo'
LspDiagnosticsUnderlineHint = 'link:DiagnosticUnderlineHint'

LspReferenceRead = '- reference'
LspReferenceText = '- reference'
LspReferenceWrite = '- reference'

IlluminatedWordRead = 'link:LspReferenceRead'
IlluminatedWordText = 'link:LspReferenceText'
IlluminatedWordWrite = 'link:LspReferenceWrite'

LspCodeLens = 'context - i'
LspCodeLensSeparator = 'context - i'

[Quickscope]
QuickScopePrimary = '#e17373 - u'
QuickScopeSecondary = '#96bddb - u'

[Telescope]
TelescopeSelection = '- dark_gray'
TelescopeSelectionCaret = 'orange -'
TelescopeMatching = 'info - bi'
TelescopeBorder = 'light_gray'
TelescopeNormal = 'fg bg'
TelescopePromptPrefix = "orange"
TelescopePromptTitle = "orange - b"
TelescopeResultsTitle = "orange - b"
TelescopePreviewTitle = "orange - b"
TelescopePromptCounter = "fg"
TelescopePreviewHyphen = "fg"

[NvimTree]
NvimTreeFolderIcon = 'link:Directory'
NvimTreeIndentMarker = 'context'
NvimTreeNormal = 'fg alt_bg'
NvimTreeVertSplit = 'alt_bg alt_bg'
NvimTreeFolderName = 'link:Directory'
NvimTreeOpenedFolderName = 'folder_blue - bi'
NvimTreeEmptyFolderName = 'gray - i'
NvimTreeGitIgnored = 'gray - i'
NvimTreeImageFile = 'dark_gray'
NvimTreeSpecialFile = 'orange'
NvimTreeEndOfBuffer = 'alt_bg'
NvimTreeCursorLine = '- line'
NvimTreeGitStaged = 'sign_add_alt'
NvimTreeGitNew = 'sign_add_alt'
NvimTreeGitRenamed = 'sign_add_alt'
NvimTreeGitDeleted = 'sign_delete'
NvimTreeGitMerge = 'sign_change_alt'
NvimTreeGitDirty = 'sign_change_alt'
NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'fg - b'
NvimTreeExecFile = '#94b978'

[Lir]
LirFloatNormal = 'fg alt_bg'
LirDir = 'link:Directory'
LirSymLink = 'cyan'
LirEmptyDirText = 'gray - i'

[Buffer]
BufferCurrent = 'fg bg'
BufferCurrentIndex = 'fg bg'
BufferCurrentMod = 'info bg'
BufferCurrentSign = 'hint bg'
BufferCurrentTarget = 'red bg b'

BufferVisible = 'fg bg'
BufferVisibleIndex = 'fg bg'
BufferVisibleMod = 'info bg'
BufferVisibleSign = 'gray bg'
BufferVisibleTarget = 'red bg b'

BufferInactive = 'gray alt_bg'
BufferInactiveIndex = 'gray alt_bg'
BufferInactiveMod = 'info alt_bg'
BufferInactiveSign = 'gray alt_bg'
BufferInactiveTarget = 'red alt_bg b'

[StatusLine]
StatusLine = 'context bg'
StatusLineNC = 'line bg'
StatusLineSeparator = 'line'
StatusLineTerm = 'line'
StatusLineTermNC = 'line'

[IndentBlankline]
IndentBlanklineContextChar = 'context'
IndentBlanklineContextStart = '- - u'
IndentBlanklineChar = 'dark_gray'
# IndentBlanklineSpaceCharBlankline = 'info'
# IndentBlanklineSpaceChar = 'cyan_test'

[Dashboard]
DashboardHeader = 'blue'
DashboardCenter = 'purple'
DashboardFooter = 'cyan'

[DiffView]
DiffViewNormal = 'gray alt_bg'
DiffviewStatusAdded = 'sign_add'
DiffviewStatusModified = 'sign_change'
DiffviewStatusRenamed = 'sign_change'
DiffviewStatusDeleted = 'sign_delete'
DiffviewFilePanelInsertion = 'sign_add'
DiffviewFilePanelDeletion = 'sign_delete'
DiffviewVertSplit = '- bg'

[Bookmarks]
BookmarkSign = 'sign_change'
BookmarkAnnotationSign = 'yellow'
BookmarkLine = 'ui2_blue'
BookmarkAnnotationLine = 'ui2_blue'

[Bqf]
BqfPreviewBorder = 'fg'
BqfPreviewRange = '- ui2_blue'
# BqfPreviewFloat = 'fg'
# BqfPreviewCursor = ''
# BqfSign = ''

[Cmp]
CmpItemAbbrDeprecated = 'gray - s'
CmpItemAbbrMatch = 'ui3_blue'
CmpItemAbbrMatchFuzzy = 'ui3_blue'

CmpItemKindFunction = 'ui_purple'
CmpItemKindMethod = 'ui_purple'
CmpItemKindConstructor = 'ui_orange'
CmpItemKindClass = 'ui_orange'
CmpItemKindEnum = 'ui_orange'
CmpItemKindEvent = 'info'
CmpItemKindInterface = 'ui_orange'
CmpItemKindStruct = 'ui_orange'
CmpItemKindVariable = 'light_blue'
CmpItemKindField = 'light_blue'
CmpItemKindProperty = 'light_blue'
CmpItemKindEnumMember = 'vivid_blue'
CmpItemKindConstant = 'vivid_blue'
CmpItemKindKeyword = 'fg'
CmpItemKindModule = 'cyan'
CmpItemKindValue = 'fg'
CmpItemKindUnit = 'fg'
CmpItemKindText = 'fg'
CmpItemKindSnippet = 'fg'
CmpItemKindFile = 'fg'
CmpItemKindFolder = 'fg'
CmpItemKindColor = 'fg'
CmpItemKindReference = 'light_blue'
CmpItemKindOperator = 'fg'
CmpItemKindTypeParameter = 'light_blue'

[Navic]
NavicIconsFile = 'link:CmpItemKindFile'
NavicIconsModule = 'link:CmpItemKindModule'
NavicIconsNamespace = 'link:CmpItemKindModule'
NavicIconsPackage = 'link:CmpItemKindModule'
NavicIconsClass = 'link:CmpItemKindClass'
NavicIconsMethod = 'link:CmpItemKindMethod'
NavicIconsProperty = 'link:CmpItemKindProperty'
NavicIconsField = 'link:CmpItemKindField'
NavicIconsConstructor = 'link:CmpItemKindConstructor'
NavicIconsEnum = 'link:CmpItemKindEnum'
NavicIconsInterface = 'link:CmpItemKindInterface'
NavicIconsFunction = 'link:CmpItemKindFunction'
NavicIconsVariable = 'link:CmpItemKindVariable'
NavicIconsConstant = 'link:CmpItemKindConstant'
NavicIconsString = 'link:String'
NavicIconsNumber = 'link:Number'
NavicIconsBoolean = 'link:Boolean'
NavicIconsArray = 'link:CmpItemKindClass'
NavicIconsObject = 'link:CmpItemKindClass'
NavicIconsKey = 'link:CmpItemKindKeyword'
NavicIconsKeyword = 'link:CmpItemKindKeyword'
NavicIconsNull = 'blue'
NavicIconsEnumMember = 'link:CmpItemKindEnumMember'
NavicIconsStruct = 'link:CmpItemKindStruct'
NavicIconsEvent = 'link:CmpItemKindEvent'
NavicIconsOperator = 'link:CmpItemKindOperator'
NavicIconsTypeParameter = 'link:CmpItemKindTypeParameter'
NavicText = 'gray'
NavicSeparator = 'context'

[Packer]
packerString = 'ui_orange'
packerHash = 'ui4_blue'
packerOutput = 'ui_purple'
packerRelDate = 'gray'
packerSuccess = 'success_green'
packerStatusSuccess = 'ui4_blue'

[SymbolOutline]
SymbolsOutlineConnector = 'gray'
FocusedSymbol = '- #292929'

[Notify]
NotifyERRORBorder = '#e17373'
NotifyWARNBorder = '#ffb97b'
NotifyINFOBorder = 'ui_blue'
NotifyDEBUGBorder = 'gray'
NotifyTRACEBorder = '#e1c0fa'
NotifyERRORIcon = 'error'
NotifyWARNIcon = 'warn'
NotifyINFOIcon = 'ui4_blue'
NotifyDEBUGIcon = 'gray'
NotifyTRACEIcon = 'ui_purple'
NotifyERRORTitle = 'error'
NotifyWARNTitle = 'warn'
NotifyINFOTitle = 'ui4_blue'
NotifyDEBUGTitle = 'gray'
NotifyTRACETitle = 'ui_purple'
# NotifyERRORBody = Normal
# NotifyWARNBody = Normal
# NotifyINFOBody = Normal
# NotifyDEBUGBody = Normal
# NotifyTRACEBody = Normal

[TreesitterContext]
TreesitterContext = '- alt_bg'

[Hop]
HopNextKey = '#96bddb'
HopNextKey1 = '#e1c0fa'
HopNextKey2 = '#fbdaff'
HopUnmatched = 'gray'
HopPreview = '#94b978'
# HopCursor = ''

[Crates]
CratesNvimLoading = 'hint'
CratesNvimVersion = 'hint'
# CratesNvimPreRelease =
# CratesNvimYanked =
# CratesNvimNoMatch =
# CratesNvimUpgrade =
# CratesNvimError =
# CratesNvimPopupPillText =
# CratesNvimPopupPillBorder =
# CratesNvimPopupDescription =
# CratesNvimPopupLabel =
# CratesNvimPopupVersion =
# CratesNvimPopupPreRelease =
# CratesNvimPopupYanked =
# CratesNvimPopupVersionDate =
# CratesNvimPopupFeature =
# CratesNvimPopupEnabled =
# CratesNvimPopupTransitive =
# CratesNvimPopupDependency =
# CratesNvimPopupOptional =
# CratesNvimPopupDependencyVersion =
# CratesNvimPopupLoading =

[Misc]
diffAdded = 'sign_add'
diffRemoved = 'sign_delete'
diffFileId = 'blue - br'
diffFile = 'alt_bg'
diffNewFile = 'green'
diffOldFile = 'red'
debugPc = '- ui5_blue'
debugBreakpoint = 'red - r'

CodiVirtualText = 'hint'
SniprunVirtualTextOk = 'hint'
SniprunFloatingWinOk = 'hint'
SniprunVirtualTextErr = 'error'
SniprunFloatingWinErr = 'error'

DapBreakpoint = 'error'

[Language]
## XML
xmlTag = 'cyan'
xmlTagName = 'cyan'

## YAML
xmlEndTag = 'cyan'
yamlPlainScalar = 'orange'
yamlTSField = 'blue'

## lua
luaFunc = 'yellow'
luaFunction = 'blue'

## hcl
hclTSPunctSpecial = 'alt_fg'

## html
htmlH1 = 'fg'
htmlH2 = 'fg'
htmlH3 = 'fg'
htmlH4 = 'fg'
htmlH5 = 'fg'
htmlH6 = 'fg'
htmlHead = 'fg'
htmlTitle = 'fg'
htmlArg = 'fg'
htmlTag = 'blue'
htmlTagN = 'blue'
htmlTagName = 'blue'
htmlComment = 'green'
htmlLink = 'orange - u'

## css
cssBraces = 'fg'
cssInclude = 'purple'
cssTagName = 'yellow'
cssClassName = 'yellow'
cssPseudoClass = 'yellow'
cssPseudoClassId = 'yellow'
cssPseudoClassLang = 'yellow'
cssIdentifier = 'yellow'
cssProp = 'fg'
cssDefinition = 'fg'
cssAttr = 'orange'
cssAttrRegion = 'orange'
cssColor = 'orange'
cssFunction = 'purple'
cssFunctionName = 'yellow'
cssVendor = 'orange'
cssValueNumber = 'orange'
cssValueLength = 'orange'
cssUnitDecorators = 'orange'
cssStyle = 'fg'
cssImportant = 'blue'

## json
jsonKeyword = 'blue'

## yaml
yamlBlockMappingKey = 'blue'

## yaml
tomlTSProperty = 'blue'
